// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lziiezzefcvddhddweel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6aWllenplZmN2ZGRoZGR3ZWVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5OTk5MDgsImV4cCI6MjA2MDU3NTkwOH0.3qua4Ux_IeEd-4Y2vNLPjq4101HZB36UB2a2Y8k4m6M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);